[gcp_service_account]
type = "service_account"
project_id = "rehab-schedule"
private_key_id = "b454492252c1b04017a8f83eba4e49aacb54d853"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCs4qnxWdexrQaf
K7Mtam6AgdCoiW6X/8eHu2Sv6wXU286Nt5T6vGpTjJhXbMhXm3bzx+LNPO0VFMkE
YCEj9TtmjufywFQa7HbaXTiaMxXP5fckgCTeLIzuYft3RKBx/wrm09GMzUd3dVRl
VblLM6T/xrnKpU80L5egl55hSJ2E5A7IE/o8c3rzzWt1/OAXNmHVoNisYBdiAtMO
SEbaX8rgQ1wNzNTHSjfGTXxkQhTku+bYJnIiysIq84PBUuf5XMhtdCaAAzFg3t3y
GllVTvn9nbZJHbTIYVrJ7Rd327tyxhkhSzFAPtCcpKMTNJx+CPp9RgvIvFyI2VD0
leNtpNdFAgMBAAECggEAMtIahMEVP7yOIsIU1LfhrdL7RF/J69Kbk9HJQlFDEJRg
vpYFrEMwukitC54FsoMXz4elqxFK3BSVFr0vYMOY54gAtQJGdvel5IDcv69erRN7
t/YXYFwWPYj+A8xfocMIMFx5z/sUFBCgc31kj6+pxCpluSUpCD0pRGLtgsl2zHZF
/FRpvVqWWHrrxQM72biI9PF7hQZjQEc4CCXoZQkOD4ntu0o7QBaaODmLmkUDV22N
+QePROM5pHFJvv1aZ9phmVg9RzPVl2Y+uBF5fIe7jPonF52gYFfE/EhHsXl9oK+P
z5E1YQ1tvy8BUAVgNHFKrv2f0rz05YnxDTE/ZfamjQKBgQDbIcEtCUJIRY52Ck2N
54Ui0ulEcmIbUHg+inq1edRTte/SXq7SEU+1TqA5q3uu9ikkO7VRXyJl6JBlELzR
hGJrRXLut/rkic7s8oy4Y67lOVcZ1CrOhtrF0DvxUP0Fh9ISG4uhWfHRzWbA4JU0
iyKN03i/aKQL1hLhltYaT6nbewKBgQDJ+QZaT+CbrywtzdG59KJC253wjBa5T/NQ
lHemyRCgccBW1wXKwz4GDQ3h6ytlD/R6NVtslOcWbvhzqkJ8SGX+VZKY8J0Q4UUX
3M04JuHRR2+NN9pNhSXucfKv/r//+K11r6O5Rquf1F/UJtBAQkqXIQwnmgj8PotL
RfWEDgU8PwKBgFKBE/2D5evWHHw/BtIt4EerR16Y/m0wUAWkF+1p8FKQRrpbIdE/
6VXnQ5ZTBV9rmTPmMy9u9UGPXYZf1efAw1mGLW7J4HHZnQpDjE4EYh42B6BW7MMT
rR0beOYzywAhEiv1KQ5YEh8fCdgG9sZwuFLT0zumB1XZhQRgyT3gzqAvAoGAPVi4
R0Iv1NnWL2tuom7dwjT2uhOy60KPgxA1b6FuvW0PoNDa34WCF1BrwQ0vNxkrhtsi
E87+id/W8zrpytoqsJ/JUU70RiZGWEMmykF1IZ3zEg++7QDeTpipwC8+nj8oYLCi
qCoBAyD8onHPm1UHVvQgvv6YcBWHNavgMOYZTP0CgYEAsXs7INSTcJubmv48LcMT
g2WvbvAX+nofdRwYoD3fbKraqt7I9BpzTikv4r+s1vZJHvRteRe3+aXlJnGojf6V
lrZM7fBCF0qdLa3YPlm8PmxIk4HttKksjFEos/XRUujkTNVp8kQDcK8zxLzGZg73
4jLtisuPdrt42mB+kUuP1KA=
-----END PRIVATE KEY-----"""
client_email = "rehab-schedule-reader@rehab-schedule.iam.gserviceaccount.com"
client_id = "106470439705858358620"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/rehab-schedule-reader%40rehab-schedule.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
